[package]
name = "dog-bot"
version = "0.1.0"
authors = ["shinichi kogai <kogai0121@gmail.com>"]

[dependencies]
dotenv = "0.10.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
hyper = "0.10.9"
hyper-native-tls = "0.2.2"
iron = "0.5.1"
router = "0.5.1"
job_scheduler = "1.0.2"
regex = "0.2"
